### ISSUE TITLE
Please add key code 0..9

### ISSUE THREAD

**Issue by Kat-CeDe** [unfoldedcircle/integration-androidtv#33]
### Description

Please add KEYCODE_0..KEYCODE_9 to ucapi. These are very important for IPTV on Android TV and they are also working on your Shield. I already tested with external integration.

**Comment by zehnm** [comment]
I've started the feature enhancements in branch `feat/27_new-feat-cmds` with mapping media-player commands `DIGIT_0..9` to Android TV `KEYCODE_NUMPAD_0..9`.
Could you please test in your external integration if `KEYCODE_NUMPAD_#` is handled the same as `KEYCODE_#`?
Otherwise I'll change the mapping to KEYCODE_#

**Comment by Kat-CeDe** [comment]
Integration is started I can test this evening.

Ralf

**Comment by Kat-CeDe** [comment]
Curious only 2 and 8 were working. It is no alternative for KEYCODE_0..9. I saw you prepared profiles I will test this evening. I think this will be more or less the final version at some time so please could you add the following app launch link:
    "Kodi": {"url": "market://launch?id=org.xbmc.kodi"},

Ralf

**Comment by zehnm** [comment]
Thanks for testing, I'll change it to `KEYCODE_0..9`.
